# Generated by Django 6.0.7 on 2026-07-19 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=55)),
                ('l_name', models.CharField(max_length=55)),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('adress', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('level', models.CharField(choices=[('JUNIOR', 'junior'), ('MIDDLE', 'middle'), ('SENIOR', 'senior')], default='JUNIOR', max_length=55)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('branch', models.CharField(max_length=55)),
                ('status', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='crm.course')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='crm.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor_enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollss', to='crm.group')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolll', to='crm.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=55)),
                ('l_name', models.CharField(max_length=55)),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('adress', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade_Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('cr_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradess', to='crm.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradee', to='crm.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField()),
                ('cr_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='crm.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='crm.student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('FINISHED', 'finished'), ('NO ACTIVE', 'no active')], default='no active', max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolls', to='crm.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enroll', to='crm.student')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('weekday', models.CharField(choices=[('DUSHANBE', 'dushanbe'), ('SESHANBE', 'seshanbe'), ('CHORSHANBE', 'chorshanbe'), ('PANJSHANBE', 'panjshanbe'), ('JUMA', 'juma'), ('SHANBE', 'shanbe'), ('YAKSHANBE', 'yakshanbe')], max_length=20)),
                ('type', models.CharField(choices=[('PRACTICE', 'practice'), ('EXAM', 'exam')], default='PRACTICE', max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='crm.group')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='crm.student')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activitys', to='crm.timetable')),
            ],
        ),
    ]
