# Generated by Django 6.0.7 on 2026-07-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_grade_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='type',
            field=models.CharField(choices=[('practice', 'Practice'), ('exam', 'Exam')], default='PRACTICE', max_length=50),
        ),
    ]
