# Generated by Django 6.0.7 on 2026-07-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_timetable_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='type',
            field=models.CharField(choices=[('PRACTICE', 'PRACTICE'), ('EXAM', 'EXAM')], default='PRACTICE', max_length=50),
        ),
    ]
